package com.guods.springboot.model;

import java.io.Serializable;

public class BookItem implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_item.ID
     *
     * @mbggenerated Tue Nov 14 13:08:58 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_item.ISBN
     *
     * @mbggenerated Tue Nov 14 13:08:58 CST 2017
     */
    private String isbn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_item.NAME
     *
     * @mbggenerated Tue Nov 14 13:08:58 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_item.DANGDANG_URL
     *
     * @mbggenerated Tue Nov 14 13:08:58 CST 2017
     */
    private String dangdangUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_item.DESCRIPTION
     *
     * @mbggenerated Tue Nov 14 13:08:58 CST 2017
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table book_item
     *
     * @mbggenerated Tue Nov 14 13:08:58 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_item.ID
     *
     * @return the value of book_item.ID
     *
     * @mbggenerated Tue Nov 14 13:08:58 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_item.ID
     *
     * @param id the value for book_item.ID
     *
     * @mbggenerated Tue Nov 14 13:08:58 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_item.ISBN
     *
     * @return the value of book_item.ISBN
     *
     * @mbggenerated Tue Nov 14 13:08:58 CST 2017
     */
    public String getIsbn() {
        return isbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_item.ISBN
     *
     * @param isbn the value for book_item.ISBN
     *
     * @mbggenerated Tue Nov 14 13:08:58 CST 2017
     */
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_item.NAME
     *
     * @return the value of book_item.NAME
     *
     * @mbggenerated Tue Nov 14 13:08:58 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_item.NAME
     *
     * @param name the value for book_item.NAME
     *
     * @mbggenerated Tue Nov 14 13:08:58 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_item.DANGDANG_URL
     *
     * @return the value of book_item.DANGDANG_URL
     *
     * @mbggenerated Tue Nov 14 13:08:58 CST 2017
     */
    public String getDangdangUrl() {
        return dangdangUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_item.DANGDANG_URL
     *
     * @param dangdangUrl the value for book_item.DANGDANG_URL
     *
     * @mbggenerated Tue Nov 14 13:08:58 CST 2017
     */
    public void setDangdangUrl(String dangdangUrl) {
        this.dangdangUrl = dangdangUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_item.DESCRIPTION
     *
     * @return the value of book_item.DESCRIPTION
     *
     * @mbggenerated Tue Nov 14 13:08:58 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_item.DESCRIPTION
     *
     * @param description the value for book_item.DESCRIPTION
     *
     * @mbggenerated Tue Nov 14 13:08:58 CST 2017
     */
    public void setDescription(String description) {
        this.description = description;
    }
}