package com.guods.springboot.model;

import java.io.Serializable;

public class CatalogBak implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catalog_bak.ID
     *
     * @mbggenerated Tue Nov 14 13:08:58 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catalog_bak.CODE
     *
     * @mbggenerated Tue Nov 14 13:08:58 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catalog_bak.NAME
     *
     * @mbggenerated Tue Nov 14 13:08:58 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table catalog_bak
     *
     * @mbggenerated Tue Nov 14 13:08:58 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catalog_bak.ID
     *
     * @return the value of catalog_bak.ID
     *
     * @mbggenerated Tue Nov 14 13:08:58 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catalog_bak.ID
     *
     * @param id the value for catalog_bak.ID
     *
     * @mbggenerated Tue Nov 14 13:08:58 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catalog_bak.CODE
     *
     * @return the value of catalog_bak.CODE
     *
     * @mbggenerated Tue Nov 14 13:08:58 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catalog_bak.CODE
     *
     * @param code the value for catalog_bak.CODE
     *
     * @mbggenerated Tue Nov 14 13:08:58 CST 2017
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catalog_bak.NAME
     *
     * @return the value of catalog_bak.NAME
     *
     * @mbggenerated Tue Nov 14 13:08:58 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catalog_bak.NAME
     *
     * @param name the value for catalog_bak.NAME
     *
     * @mbggenerated Tue Nov 14 13:08:58 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }
}