package com.guods.springboot.model;

import java.io.Serializable;

public class Catalog implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catalog.ID
     *
     * @mbggenerated Tue Nov 14 13:08:58 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catalog.CODE
     *
     * @mbggenerated Tue Nov 14 13:08:58 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table catalog
     *
     * @mbggenerated Tue Nov 14 13:08:58 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catalog.ID
     *
     * @return the value of catalog.ID
     *
     * @mbggenerated Tue Nov 14 13:08:58 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catalog.ID
     *
     * @param id the value for catalog.ID
     *
     * @mbggenerated Tue Nov 14 13:08:58 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catalog.CODE
     *
     * @return the value of catalog.CODE
     *
     * @mbggenerated Tue Nov 14 13:08:58 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catalog.CODE
     *
     * @param code the value for catalog.CODE
     *
     * @mbggenerated Tue Nov 14 13:08:58 CST 2017
     */
    public void setCode(String code) {
        this.code = code;
    }
}