package com.guods.springboot.mapper;

import com.guods.springboot.model.BookItem;
import java.util.List;

public interface BookItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_item
     *
     * @mbggenerated Tue Nov 14 13:08:58 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_item
     *
     * @mbggenerated Tue Nov 14 13:08:58 CST 2017
     */
    int insert(BookItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_item
     *
     * @mbggenerated Tue Nov 14 13:08:58 CST 2017
     */
    BookItem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_item
     *
     * @mbggenerated Tue Nov 14 13:08:58 CST 2017
     */
    List<BookItem> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_item
     *
     * @mbggenerated Tue Nov 14 13:08:58 CST 2017
     */
    int updateByPrimaryKey(BookItem record);
}